/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:451992:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel1:451992:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:498275:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
  panel1.setVisible(false);
  inputType = "mouse";
  reset();
} //_CODE_:imgButton1:498275:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:468414:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
  panel1.setVisible(false);
  inputType = "tap";
  reset();
} //_CODE_:imgButton2:468414:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:522270:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
  panel1.setVisible(false);
  inputType = "shout";
  reset();
} //_CODE_:imgButton3:522270:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  panel1 = new GPanel(this, 22, 61, 454, 278, "");
  panel1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  imgButton1 = new GImageButton(this, -9, 84, new String[] { "mouseOff.png", "mouseOn.png", "mouseOn.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  label1 = new GLabel(this, 131, 33, 175, 26);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choose an input style");
  label1.setTextBold();
  label1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label1.setOpaque(true);
  label2 = new GLabel(this, 13, 216, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Mouse");
  label2.setOpaque(false);
  imgButton2 = new GImageButton(this, 140, 79, new String[] { "touchOff.png", "touchOn.png", "touchOn.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  label3 = new GLabel(this, 168, 215, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Tap");
  label3.setOpaque(false);
  imgButton3 = new GImageButton(this, 309, 85, 128, 128, new String[] { "shoutOff.png", "shoutOn.png", "shoutOn.png" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
  label4 = new GLabel(this, 327, 213, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Shout");
  label4.setOpaque(false);
  panel1.addControl(imgButton1);
  panel1.addControl(label1);
  panel1.addControl(label2);
  panel1.addControl(imgButton2);
  panel1.addControl(label3);
  panel1.addControl(imgButton3);
  panel1.addControl(label4);
}

// Variable declarations 
// autogenerated do not edit
GPanel panel1; 
GImageButton imgButton1; 
GLabel label1; 
GLabel label2; 
GImageButton imgButton2; 
GLabel label3; 
GImageButton imgButton3; 
GLabel label4; 